image: node:16

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - yarn install
    - yarn run build
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - rm -rf public
    - mkdir public
    - mv -v build/* public
    - ls -l public
  artifacts:
    paths:
      - public
  only:
    - master