image: node:16

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - yarn install
    - yarn run build
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - ls -l
    - mkdir .public
    - ls -l
    - cp -r * .public
    - ls -l
    - mv .public public
    - ls -l public
  artifacts:
    paths:
      - public
  only:
    - master