image: node:16

stages:
  - build
  - deploy

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - CI=false yarn install
    - CI=false yarn run build
    - rm -rf public
    - mkdir public
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - mv -v build/* public
  artifacts:
    paths:
      - public
  only:
    - master