image: node

pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - rm -rf public
    - cp -r * .build
    - mv .build public
  artifacts:
    paths:
      - public
  only:
    - master