image: node:17

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - rm -rf public
    - cp -r * .build
    - mv .build public
  artifacts:
    paths:
      - public
  only:
    - master