image: node:16

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - yarn install
    - yarn run build
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - rm -rf public
    - ls -l
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master