language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build

#install:
#  - npm install
#  - npm install codecov -g
#env:
#  - CODECOV_TOKEN=$CODECOV_TOKEN
#scripts:
#  - CI=true npm run test:unit --reporters=jest-junit --coverage --no-cache
#  - codecov -f coverage/*.json
#after_success:
#  - codecov


