language: node_js
node_js:
  - 17
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install codecov -g
env:
  - CODECOV_TOKEN=$CODECOV_TOKEN
script:
  - CI=true npm run test:unit --reporters=jest-junit
  - codecov -f coverage/*.json



