language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install codecov -g
env:
  - CODECOV_TOKEN=$CODECOV_TOKEN
script:
  - CI=true npm run test:unit --reporters=jest-junit --coverage --no-cache
  - codecov -f coverage/*.json
after_success:
  - codecov



